version: 2
jobs:
  build:
    docker:
      - image: coqorg/coq:8.10.2
    steps:
      - checkout
      - run: |
          source ~/.profile
          ./configure.sh
          make
          make html
      - persist_to_workspace:
          root: .
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@example.com"
            git config user.name "ci-build"
      - run: ls -la
      - add_ssh_keys:
          fingerprints:
            - "d6:ca:09:9d:40:ac:77:09:6b:a0:d3:ba:74:ac:34:6b"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] doc upload" --dist html

workflows:
  version: 2
  build:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
